import { Inter } from "next/font/google";
import "./globals.css";
import SessionProvider from './components/SessionProvider'

import { getServerSession } from 'next-auth'
import Navber from "./components/Navbar";
import Footer from "./components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Cat POS System",
  // description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <body className={inter.className}>
      <Navber/>
        <SessionProvider session={session}>
          {children}
        </SessionProvider>
        <Footer/>
      </body>
    </html>
  );
}
